# Generated by Django 4.2.11 on 2024-04-01 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.FloatField(default=0.0)),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Date')),
                ('status', models.CharField(choices=[('placed', 'Placed'), ('preparing', 'Preparing'), ('ready', 'Ready'), ('delivered', 'Delivered')], max_length=50, verbose_name='Order Status')),
            ],
        ),
    ]
