# Generated by Django 4.2.11 on 2024-04-01 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.URLField(default='', max_length=256, verbose_name='Dish image')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Dish name')),
                ('price', models.FloatField(default=0)),
                ('description', models.CharField(default='', max_length=500, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.URLField(default='', max_length=256, verbose_name='Restaurant Image')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Restaurant Name')),
                ('location', models.CharField(default='', max_length=255, verbose_name='Location')),
                ('cuisine', models.CharField(default='', max_length=200, verbose_name='Cuisine')),
            ],
        ),
    ]
